language: node_js
# This is a lie, but we want to use Node for testing
node_js:
  - "0.11"

before_install:
  - sudo apt-get update -y
  - sudo add-apt-repository ppa:ondrej/php5 -y
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install php5 -y
  - npm install -g grunt-cli
  - cd $HOME
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.2
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - cd $TRAVIS_BUILD_DIR
